### ISSUE TITLE
how is it supposed to be built/executed?

### ISSUE THREAD

**Issue by laf0rge** [markopolo123/gpsd_prometheus_exporter#4]
The README.md file indicates an executable file called `gpsd-exporter` should be created. But it is not part of the git repo, and it is not obvious how this file should be generated?

It appears I'm not up-to-date with modern python projects that don't have a setup.py file or work directly with setuptools.  I've tried to `poetry install` but that fails as  it claims the lock file is not in sync. doing `poetry lock` followed by `poetry install` works, but I still don't get the `gpsd-exporter` command that I can run.

What am I missing? Any help is appreciated.

**Comment by markopolo123** [comment]
Hi @laf0rge, 
it's on `https://pypi.org/` as `https://pypi.org/project/gpsd-prometheus-exporter/`
so you can install using poetry or pip etc. 

**If building, the following should see you sorted:**

➜  poetry install
Installing dependencies from lock file

Package operations: 20 installs, 0 updates, 0 removals

  • Installing appdirs (1.4.4)
  • Installing attrs (22.2.0)
  • Installing click (8.1.3)
  • Installing iniconfig (2.0.0)
  • Installing mypy-extensions (0.4.3)
  • Installing packaging (23.0)
  • Installing pathspec (0.10.3)
  • Installing pluggy (1.0.0)
  • Installing py (1.11.0)
  • Installing regex (2022.10.31)
  • Installing toml (0.10.2)
  • Installing typed-ast (1.5.4)
  • Installing typing-extensions (4.4.0)
  • Installing argparse (1.4.0)
  • Installing black (20.8b1)
  • Installing bump2version (1.0.1)
  • Installing gps (3.19)
  • Installing gpsd-py3 (0.3.0)
  • Installing prometheus-client (0.9.0)
  • Installing pytest (6.2.5)

Installing the current project: gpsd_prometheus_exporter (0.3.1)

➜  poetry build

Building gpsd_prometheus_exporter (0.3.1)
  - Building sdist
  - Built gpsd_prometheus_exporter-0.3.1.tar.gz
  - Building wheel
  - Built gpsd_prometheus_exporter-0.3.1-py3-none-any.whl


➜  poetry run gpsd-exporter
```
